apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollout-app
  template:
    metadata:
      labels:
        app: rollout-app
    spec:
      containers:
        - name: rollout-container
          image: laly9999/sample-app:14
          ports:
            - name: http
              containerPort: 3000
  strategy:
    blueGreen:
      activeService: svc-active
      previewService: svc-preview
      autoPromotionEnabled: false


